$ref: "#/$defs/event"
$defs:
  event:
    type: object
    additionalProperties: false
    required:
      - id
      - date
      - city
      - country
    properties:
      id:
        type: string
      type:
        type: string
        enum:
          - summit
          - meetup
          - hackathon
      date:
        type: string
      days:
        type: number
      city:
        type: string
      country:
        type: string
        pattern: "^\\w{2}$"
      coincidence:
        type: string
      lead:
        type: string
      helpers:
        type: array
        items:
          type: string
      slots:
        type: number
      visitors:
        type: number
      optional:
        type: boolean
      links:
        type: object
        additionalProperties: false
        patternProperties:
          "^[\\w]+":
            type: string
            format: uri